"""create tenants table

Revision ID: fd8e2dc0564a
Revises: 
Create Date: 2026-09-08 11:22:18.141228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8e2dc0564a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('instagram_handle', sa.String(), nullable=True),
    sa.Column('tone_settings', sa.JSON(), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('embedding_provider', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    # ### end Alembic commands ###
